name: test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: print wdir
            run: pwd
                touch test_file.txt
                mkdir path
